//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "XmlBonuscellReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "XmlBonuscell.h"


namespace ww2024
{
XmlBonuscellReader::XmlBonuscellReader()
{
}


std::unique_ptr<XmlBonuscell> XmlBonuscellReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto bonuscell = std::make_unique<XmlBonuscell>();
    Fill(anElement, *bonuscell);
    return bonuscell;
}

XmlClass::Result XmlBonuscellReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlBonuscell & aBonuscell)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* gewichtnode = attributes->getNamedItem(L"gewicht");
    if (gewichtnode != nullptr) {
        aBonuscell.Setgewicht(_wtoi(gewichtnode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* intensiteitnode = attributes->getNamedItem(L"intensiteit");
    if (intensiteitnode != nullptr)
    {
      if (wcscmp(intensiteitnode->getNodeValue(), L"laag") == 0)
        aBonuscell.Setintensiteit(XmlBonuscell::intensiteit::laag);
      else if (wcscmp(intensiteitnode->getNodeValue(), L"middel") == 0)
        aBonuscell.Setintensiteit(XmlBonuscell::intensiteit::middel);
      else if (wcscmp(intensiteitnode->getNodeValue(), L"hoog") == 0)
        aBonuscell.Setintensiteit(XmlBonuscell::intensiteit::hoog);
    }
    const XERCES_CPP_NAMESPACE::DOMNode* minutennode = attributes->getNamedItem(L"minuten");
    if (minutennode != nullptr) {
        aBonuscell.Setminuten(_wtoi(minutennode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* puntennode = attributes->getNamedItem(L"punten");
    if (puntennode != nullptr) {
        aBonuscell.Setpunten(_wtoi(puntennode->getNodeValue()));
    }
    }

    return XmlClass::Result::Ok;
}


}
