//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "XmlBonuscellWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "XmlBonuscell.h"

namespace ww2024
{
XERCES_CPP_NAMESPACE::DOMNode * XmlBonuscellWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlBonuscell & aBonuscell)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"bonuscell");
    Fill(aDocument, aBonuscell, *element);
    return element;
}

void XmlBonuscellWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlBonuscell & aBonuscell, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aBonuscell;
    (void)anElement;
    {
        auto buffer{ std::to_wstring(aBonuscell.Getgewicht()) };
        anElement.setAttribute(L"gewicht", buffer.c_str());
    }
    switch (aBonuscell.Getintensiteit())
    {
        case XmlBonuscell::intensiteit::laag:
            anElement.setAttribute(L"intensiteit", L"laag");
        break;
        case XmlBonuscell::intensiteit::middel:
            anElement.setAttribute(L"intensiteit", L"middel");
        break;
        case XmlBonuscell::intensiteit::hoog:
            anElement.setAttribute(L"intensiteit", L"hoog");
        break;
        default:
            throw 1;
    }
    {
        auto buffer{ std::to_wstring(aBonuscell.Getminuten()) };
        anElement.setAttribute(L"minuten", buffer.c_str());
    }
    {
        auto buffer{ std::to_wstring(aBonuscell.Getpunten()) };
        anElement.setAttribute(L"punten", buffer.c_str());
    }
}


}
