//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "XmlPersonaliaWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "XmlPersonalia.h"

namespace ww2024
{
XmlClass::Result XmlPersonaliaWriter::Write(const std::string & aFilename, const XmlPersonalia & aPersonalia)
{
    ParseErrorHandler eh;
    XERCES_CPP_NAMESPACE::XercesDOMParser parser;
    parser.setDoValidation(false);
    parser.setErrorHandler(&eh);

    XERCES_CPP_NAMESPACE::DOMImplementation* impl =
      XERCES_CPP_NAMESPACE::DOMImplementationRegistry::getDOMImplementation(L"Core");

    XERCES_CPP_NAMESPACE::DOMDocument* doc =
      impl->createDocument(0,               // root element namespace URI.
                           L"personalia",  // root element name
                           0);              // document type object (Xml).
    XERCES_CPP_NAMESPACE::DOMElement* rootelement = doc->getDocumentElement();
    Fill(*doc, aPersonalia, *rootelement);

    XERCES_CPP_NAMESPACE::DOMWriter* writer = ((XERCES_CPP_NAMESPACE::DOMImplementationLS*)impl)->createDOMWriter();
    XERCES_CPP_NAMESPACE::LocalFileFormatTarget formatter(aFilename.c_str());
    writer->writeNode(&formatter, *doc);
    writer->release();

    doc->release();

    return Result::Ok;
}


void XmlPersonaliaWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlPersonalia & aPersonalia, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aPersonalia;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aPersonalia.Getnaam()).c_str());
  anElement.setAttribute(L"gebruikersnaam", Str::ToWString(aPersonalia.Getgebruikersnaam()).c_str());
    {
        auto buffer{ std::to_wstring(aPersonalia.Getkcpunten()) };
        anElement.setAttribute(L"kcpunten", buffer.c_str());
    }
    {
        auto buffer{ std::to_wstring(aPersonalia.Getkcweekpunten()) };
        anElement.setAttribute(L"kcweekpunten", buffer.c_str());
    }
    {
        auto buffer{ std::to_wstring(aPersonalia.Getchpunten()) };
        anElement.setAttribute(L"chpunten", buffer.c_str());
    }
    {
        auto buffer{ std::to_wstring(aPersonalia.Getchweekpunten()) };
        anElement.setAttribute(L"chweekpunten", buffer.c_str());
    }
  anElement.setAttribute(L"geboren", Str::ToWString(aPersonalia.Getgeboren()).c_str());
    switch (aPersonalia.Getgeslacht())
    {
        case XmlPersonalia::geslacht::Mannelijk:
            anElement.setAttribute(L"geslacht", L"Mannelijk");
        break;
        case XmlPersonalia::geslacht::Vrouwelijk:
            anElement.setAttribute(L"geslacht", L"Vrouwelijk");
        break;
        default:
            throw 1;
    }
    switch (aPersonalia.Getwerk())
    {
        case XmlPersonalia::werk::Zittend:
            anElement.setAttribute(L"werk", L"Zittend");
        break;
        case XmlPersonalia::werk::Staand:
            anElement.setAttribute(L"werk", L"Staand");
        break;
        case XmlPersonalia::werk::Lopend:
            anElement.setAttribute(L"werk", L"Lopend");
        break;
        case XmlPersonalia::werk::Zwaar:
            anElement.setAttribute(L"werk", L"Zwaar");
        break;
        default:
            throw 1;
    }
    {
        auto buffer{ std::to_wstring(aPersonalia.Getlengte()) };
        anElement.setAttribute(L"lengte", buffer.c_str());
    }
    {
        auto buffer{ std::to_wstring(aPersonalia.Getgewicht()) };
        anElement.setAttribute(L"gewicht", buffer.c_str());
    }
    {
        auto buffer{ std::to_wstring(aPersonalia.Getstreefgewicht()) };
        anElement.setAttribute(L"streefgewicht", buffer.c_str());
    }
    {
        auto buffer{ std::to_wstring(aPersonalia.Getstartgewicht()) };
        anElement.setAttribute(L"startgewicht", buffer.c_str());
    }
    {
        auto buffer{ std::to_wstring(aPersonalia.Gethuidiggewicht()) };
        anElement.setAttribute(L"huidiggewicht", buffer.c_str());
    }
    switch (aPersonalia.Getstrategie())
    {
        case XmlPersonalia::strategie::KCal:
            anElement.setAttribute(L"strategie", L"KCal");
        break;
        case XmlPersonalia::strategie::CarboHydrates:
            anElement.setAttribute(L"strategie", L"CarboHydrates");
        break;
        default:
            throw 1;
    }
}


}
