//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlModelReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "XmlPersonaliaReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>
#include <xercesc/sax/saxexception.hpp>
#include "XmlPersonalia.h"
namespace ww2024
{


XmlPersonaliaReader::XmlPersonaliaReader()
{
}


std::unique_ptr<XmlPersonalia> XmlPersonaliaReader::Read(const std::string & aFilename)
{
    if (_access(aFilename.c_str(), 0) == -1)
      {
          switch (errno)
          {
              case ENOENT:
                  throw Result::FileNotFound;
              default:
                  throw Result::FileOpenError;
          }
      }

    ParseErrorHandler eh;
    XERCES_CPP_NAMESPACE::XercesDOMParser parser;
    parser.setDoValidation(false);
    parser.setErrorHandler(&eh);

    Result result = ParseDocument(aFilename, parser);
    if (result != Result::Ok)
        if (result == Result::FileNotFound)
            return {};
        else
            throw result;

    if (parser.getDocument() == nullptr)
        throw Result::ErrorInFile;

    try
    {
        XERCES_CPP_NAMESPACE::DOMNodeList * list = parser.getDocument()->getChildNodes();

        if (list == nullptr)
            throw Result::ErrorInFile;

        for (XMLSize_t i = 0; i < list->getLength(); i++)
        {
            if (list->item(i) == nullptr)
                continue;

            short type = list->item(i)->getNodeType();
            XERCES_CPP_NAMESPACE::DOMNode * node = list->item(i);

            if (type == XERCES_CPP_NAMESPACE::DOMNode::TEXT_NODE)
            {
                continue;
            }
            else if (type == XERCES_CPP_NAMESPACE::DOMNode::ELEMENT_NODE)
            {
                if (wcscmp(node->getNodeName(), L"personalia") == 0)
                    return Generate(*node);
            }
        }

        throw Result::ParserError;
    }
    catch (const std::exception & anException)
    {
        (void)anException;
        throw Result::ParserError;
    }
    catch (const XERCES_CPP_NAMESPACE::SAXException & anException)
    {
        (void)anException;
        throw Result::ParserError;
    }
    catch (...)
    {
        throw Result::ParserError;
    }

    return {};
}

std::unique_ptr<XmlPersonalia> XmlPersonaliaReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto personalia = std::make_unique<XmlPersonalia>();
    Fill(anElement, *personalia);
    return personalia;
}


XmlClass::Result XmlPersonaliaReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlPersonalia & aPersonalia)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++)
    {
        if (list->item(i) == nullptr)
            continue;

  }
    XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* naamnode = attributes->getNamedItem(L"naam");
    if (naamnode != nullptr)
      aPersonalia.Setnaam(Str::ToString(naamnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* gebruikersnaamnode = attributes->getNamedItem(L"gebruikersnaam");
    if (gebruikersnaamnode != nullptr)
      aPersonalia.Setgebruikersnaam(Str::ToString(gebruikersnaamnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* kcpuntennode = attributes->getNamedItem(L"kcpunten");
    if (kcpuntennode != nullptr) {
        aPersonalia.Setkcpunten(_wtoi(kcpuntennode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* kcweekpuntennode = attributes->getNamedItem(L"kcweekpunten");
    if (kcweekpuntennode != nullptr) {
        aPersonalia.Setkcweekpunten(_wtoi(kcweekpuntennode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* chpuntennode = attributes->getNamedItem(L"chpunten");
    if (chpuntennode != nullptr) {
        aPersonalia.Setchpunten(_wtoi(chpuntennode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* chweekpuntennode = attributes->getNamedItem(L"chweekpunten");
    if (chweekpuntennode != nullptr) {
        aPersonalia.Setchweekpunten(_wtoi(chweekpuntennode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* geborennode = attributes->getNamedItem(L"geboren");
    if (geborennode != nullptr)
      aPersonalia.Setgeboren(Str::ToString(geborennode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* geslachtnode = attributes->getNamedItem(L"geslacht");
    if (geslachtnode != nullptr)
    {
      if (wcscmp(geslachtnode->getNodeValue(), L"Mannelijk") == 0)
        aPersonalia.Setgeslacht(XmlPersonalia::geslacht::Mannelijk);
      else if (wcscmp(geslachtnode->getNodeValue(), L"Vrouwelijk") == 0)
        aPersonalia.Setgeslacht(XmlPersonalia::geslacht::Vrouwelijk);
    }
    const XERCES_CPP_NAMESPACE::DOMNode* werknode = attributes->getNamedItem(L"werk");
    if (werknode != nullptr)
    {
      if (wcscmp(werknode->getNodeValue(), L"Zittend") == 0)
        aPersonalia.Setwerk(XmlPersonalia::werk::Zittend);
      else if (wcscmp(werknode->getNodeValue(), L"Staand") == 0)
        aPersonalia.Setwerk(XmlPersonalia::werk::Staand);
      else if (wcscmp(werknode->getNodeValue(), L"Lopend") == 0)
        aPersonalia.Setwerk(XmlPersonalia::werk::Lopend);
      else if (wcscmp(werknode->getNodeValue(), L"Zwaar") == 0)
        aPersonalia.Setwerk(XmlPersonalia::werk::Zwaar);
    }
    const XERCES_CPP_NAMESPACE::DOMNode* lengtenode = attributes->getNamedItem(L"lengte");
    if (lengtenode != nullptr) {
        aPersonalia.Setlengte(_wtoi(lengtenode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* gewichtnode = attributes->getNamedItem(L"gewicht");
    if (gewichtnode != nullptr) {
        aPersonalia.Setgewicht(_wtof(gewichtnode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* streefgewichtnode = attributes->getNamedItem(L"streefgewicht");
    if (streefgewichtnode != nullptr) {
        aPersonalia.Setstreefgewicht(_wtof(streefgewichtnode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* startgewichtnode = attributes->getNamedItem(L"startgewicht");
    if (startgewichtnode != nullptr) {
        aPersonalia.Setstartgewicht(_wtof(startgewichtnode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* huidiggewichtnode = attributes->getNamedItem(L"huidiggewicht");
    if (huidiggewichtnode != nullptr) {
        aPersonalia.Sethuidiggewicht(_wtof(huidiggewichtnode->getNodeValue()));
    }
    const XERCES_CPP_NAMESPACE::DOMNode* strategienode = attributes->getNamedItem(L"strategie");
    if (strategienode != nullptr)
    {
      if (wcscmp(strategienode->getNodeValue(), L"KCal") == 0)
        aPersonalia.Setstrategie(XmlPersonalia::strategie::KCal);
      else if (wcscmp(strategienode->getNodeValue(), L"CarboHydrates") == 0)
        aPersonalia.Setstrategie(XmlPersonalia::strategie::CarboHydrates);
    }
    }

    return XmlClass::Result::Ok;
}


}


