//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "XmlUnitWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "XmlUnit.h"

namespace ww2024
{
XERCES_CPP_NAMESPACE::DOMNode * XmlUnitWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlUnit & aUnit)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"unit");
    Fill(aDocument, aUnit, *element);
    return element;
}

void XmlUnitWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlUnit & aUnit, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{
    (void)aDocument;
    (void)aUnit;
    (void)anElement;
  anElement.setAttribute(L"naam", Str::ToWString(aUnit.Getnaam()).c_str());
}


}
