//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementWriterGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================

//=================================
// Generated by XmlWriterGenerator 
//=================================

#include "XmlVoedingsmiddeldefWriter.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "XmlVoedingsmiddeldef.h"

#include "XmlVoedingswaardeWriter.h"
#include "XmlVoedingswaarde.h"
#include "XmlPortieWriter.h"
#include "XmlPortie.h"
namespace ww2024
{
XERCES_CPP_NAMESPACE::DOMNode * XmlVoedingsmiddeldefWriter::Write(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddeldef & aVoedingsmiddeldef)
{
    XERCES_CPP_NAMESPACE::DOMElement * element = aDocument.createElement(L"voedingsmiddeldef");
    Fill(aDocument, aVoedingsmiddeldef, *element);
    return element;
}

void XmlVoedingsmiddeldefWriter::Fill(XERCES_CPP_NAMESPACE::DOMDocument & aDocument, const XmlVoedingsmiddeldef & aVoedingsmiddeldef, XERCES_CPP_NAMESPACE::DOMElement & anElement)
{

    XmlVoedingswaardeWriter Voedingswaardewriter;
    anElement.appendChild(Voedingswaardewriter.Write(aDocument, aVoedingsmiddeldef.GetVoedingswaarde()));

    XmlPortieWriter Portiewriter;
    for (size_t i = 0; i < aVoedingsmiddeldef.GetPortieList().size(); ++i)
    {
        XERCES_CPP_NAMESPACE::DOMNode * Portienode = Portiewriter.Write(aDocument, *aVoedingsmiddeldef.GetPortieList()[i]);
        anElement.appendChild(Portienode);
    }
  anElement.setAttribute(L"naam", Str::ToWString(aVoedingsmiddeldef.Getnaam()).c_str());
  anElement.setAttribute(L"categorie", Str::ToWString(aVoedingsmiddeldef.Getcategorie()).c_str());
  if (!aVoedingsmiddeldef.Getmerk().empty())
    anElement.setAttribute(L"merk", Str::ToWString(aVoedingsmiddeldef.Getmerk()).c_str());
  anElement.setAttribute(L"unit", Str::ToWString(aVoedingsmiddeldef.Getunit()).c_str());
    switch (aVoedingsmiddeldef.Getfavoriet())
    {
        case XmlVoedingsmiddeldef::favoriet::yes:
            anElement.setAttribute(L"favoriet", L"yes");
        break;
        case XmlVoedingsmiddeldef::favoriet::no:
            anElement.setAttribute(L"favoriet", L"no");
        break;
        default:
            throw 1;
    }
}


}
