//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "XmlVoedingsmiddelReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "XmlVoedingsmiddel.h"
#include "XmlPortieReader.h"
#include "XmlPortie.h"
#include "XmlVoedingswaardeReader.h"
#include "XmlVoedingswaarde.h"


namespace ww2024
{
XmlVoedingsmiddelReader::XmlVoedingsmiddelReader()
{
}


std::unique_ptr<XmlVoedingsmiddel> XmlVoedingsmiddelReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto voedingsmiddel = std::make_unique<XmlVoedingsmiddel>();
    Fill(anElement, *voedingsmiddel);
    return voedingsmiddel;
}

XmlClass::Result XmlVoedingsmiddelReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlVoedingsmiddel & aVoedingsmiddel)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

        short type = list->item(i)->getNodeType();
        XERCES_CPP_NAMESPACE::DOMNode * node = list->item(i);

        if (type == XERCES_CPP_NAMESPACE::DOMNode::ELEMENT_NODE) {
     if (wcscmp(node->getNodeName(), L"portie") == 0)
     {
         XmlPortieReader portieReader;
         auto portie = portieReader.Generate(*node);
         if (portie != nullptr)
             aVoedingsmiddel.Setportie(std::move(portie)); 
     }
     else if (wcscmp(node->getNodeName(), L"voedingswaarde") == 0)
     {
         XmlVoedingswaardeReader voedingswaardeReader;
         auto voedingswaarde = voedingswaardeReader.Generate(*node);
         if (voedingswaarde != nullptr)
             aVoedingsmiddel.Setvoedingswaarde(std::move(voedingswaarde)); 
     }
   }
  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* naamnode = attributes->getNamedItem(L"naam");
    if (naamnode != nullptr)
      aVoedingsmiddel.Setnaam(Str::ToString(naamnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* categorienode = attributes->getNamedItem(L"categorie");
    if (categorienode != nullptr)
      aVoedingsmiddel.Setcategorie(Str::ToString(categorienode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* unitnode = attributes->getNamedItem(L"unit");
    if (unitnode != nullptr)
      aVoedingsmiddel.Setunit(Str::ToString(unitnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* aantalportiesnode = attributes->getNamedItem(L"aantalporties");
    if (aantalportiesnode != nullptr) {
        aVoedingsmiddel.Setaantalporties(_wtof(aantalportiesnode->getNodeValue()));
    }
    }

    return XmlClass::Result::Ok;
}


}
