//=================================================
// GENERATED FILE, DON'T CHANGE MANUALLY
// GENERATED BY XmlElementReaderGenerator
// To modify, adapt and run the XercesCodeGenerator
//=================================================
#include "XmlVoedingsmiddeldefReader.h"

#include <xercesc/dom/dom.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include <Utilities/strutils.h>

#include "XmlVoedingsmiddeldef.h"
#include "XmlVoedingswaardeReader.h"
#include "XmlVoedingswaarde.h"
#include "XmlPortieReader.h"
#include "XmlPortie.h"


namespace ww2024
{
XmlVoedingsmiddeldefReader::XmlVoedingsmiddeldefReader()
{
}


std::unique_ptr<XmlVoedingsmiddeldef> XmlVoedingsmiddeldefReader::Generate(const XERCES_CPP_NAMESPACE::DOMNode & anElement)
{
    auto voedingsmiddeldef = std::make_unique<XmlVoedingsmiddeldef>();
    Fill(anElement, *voedingsmiddeldef);
    return voedingsmiddeldef;
}

XmlClass::Result XmlVoedingsmiddeldefReader::Fill(const XERCES_CPP_NAMESPACE::DOMNode & anElement, XmlVoedingsmiddeldef & aVoedingsmiddeldef)
{
    const XERCES_CPP_NAMESPACE::DOMNodeList * list = anElement.getChildNodes();

    if (list == nullptr)
        return XmlClass::Result::Ok;

    for (XMLSize_t i = 0; i < list->getLength(); i++) {
        if (list->item(i) == nullptr)
            continue;

        short type = list->item(i)->getNodeType();
        XERCES_CPP_NAMESPACE::DOMNode * node = list->item(i);

        if (type == XERCES_CPP_NAMESPACE::DOMNode::ELEMENT_NODE) {
     if (wcscmp(node->getNodeName(), L"voedingswaarde") == 0)
     {
         XmlVoedingswaardeReader voedingswaardeReader;
         auto voedingswaarde = voedingswaardeReader.Generate(*node);
         if (voedingswaarde != nullptr)
             aVoedingsmiddeldef.Setvoedingswaarde(std::move(voedingswaarde)); 
     }
     else if (wcscmp(node->getNodeName(), L"portie") == 0)
     {
         XmlPortieReader portieReader;
         auto portie = portieReader.Generate(*node);
         if (portie != nullptr)
             aVoedingsmiddeldef.Add(std::move(portie));
     }
   }
  }
    const XERCES_CPP_NAMESPACE::DOMNamedNodeMap * attributes = anElement.getAttributes();
    if (attributes != nullptr)
    {
    const XERCES_CPP_NAMESPACE::DOMNode* naamnode = attributes->getNamedItem(L"naam");
    if (naamnode != nullptr)
      aVoedingsmiddeldef.Setnaam(Str::ToString(naamnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* categorienode = attributes->getNamedItem(L"categorie");
    if (categorienode != nullptr)
      aVoedingsmiddeldef.Setcategorie(Str::ToString(categorienode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* merknode = attributes->getNamedItem(L"merk");
    if (merknode != nullptr)
      aVoedingsmiddeldef.Setmerk(Str::ToString(merknode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* unitnode = attributes->getNamedItem(L"unit");
    if (unitnode != nullptr)
      aVoedingsmiddeldef.Setunit(Str::ToString(unitnode->getNodeValue()));
    const XERCES_CPP_NAMESPACE::DOMNode* favorietnode = attributes->getNamedItem(L"favoriet");
    if (favorietnode != nullptr)
    {
      if (wcscmp(favorietnode->getNodeValue(), L"yes") == 0)
        aVoedingsmiddeldef.Setfavoriet(XmlVoedingsmiddeldef::favoriet::yes);
      else if (wcscmp(favorietnode->getNodeValue(), L"no") == 0)
        aVoedingsmiddeldef.Setfavoriet(XmlVoedingsmiddeldef::favoriet::no);
    }
    }

    return XmlClass::Result::Ok;
}


}
